### PR TITLE
added chat component

### PR DESCRIPTION
**Pull request by xinkin**

### CODE REVIEW

**Comment by vrajdesai78** [comment]
@xinkin closing this PR, bcz you haven't created a new branch. Whenever you are creating a PR, please create a new branch like `screen-share-feature` and create a PR from it.

**Comment by xinkin** [comment]
@vrajdesai78 do you want me to create a branch in my forked repo, and push it to huddle main or make branch in the main repo?

**Comment by vrajdesai78** [comment]
> @vrajdesai78 do you want me to create a branch in my forked repo, and push it to huddle main or make branch in the main repo?
> 
> 

Create a branch in your forked repo and create a PR from that

**Comment by xinkin** [comment]
@vrajdesai78 done, please take a look when you get time.

**Pull request closed without merging**
